# 1 - build the app
FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# 2 - server with nginx
FROM nginx:alpine

# Remove default Nginx files 
RUN rm -rf /usr/share/nginx/html/*

# Copy the Vite build output / Copy the build from the first stage to the Nginx container
COPY --from=build /app/dist /usr/share/nginx/html

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose HTTP port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]