export const START_REFERRAL = "START_REFERRAL";
export const OPEN_REFERRAL_FORM = "OPEN_REFERRAL_FORM";
export const CLOSE_REFERRAL_FORM = "CLOSE_REFERRAL_FORM";
export const SET_FORM_DATA = "SET_FORM_DATA";
export const SUBMIT_REFERRAL = "SUBMIT_REFERRAL"